# Generated by Django 4.2 on 2023-04-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=50)),
                ('imsak', models.TimeField()),
                ('subuh', models.TimeField()),
                ('terbit', models.TimeField()),
                ('duha', models.TimeField()),
                ('zuhur', models.TimeField()),
                ('asar', models.TimeField()),
                ('magrib', models.TimeField()),
                ('isya', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
